version: '3'
services:
  imdb-database:
    container_name: imdb_database
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ioasys
      POSTGRES_PASSWORD: ioasys
      POSTGRES_DB: imdb
    restart: always
    ports:
      - "5432:5432"
  imdb-service:
    container_name: imdb_service
    image: imdb-service
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - imdb-database
    ports:
      - "8080:8080"
    restart: always
    links:
      - imdb-database
