jwt:
  expiration: 14400000
  secret: t7w!z%C*F-JaNdRgUkXp2s5v8x/A?D(G+KbPeShVmYq3t6w9z$B&E)H@McQfTjWn
spring:
  datasource:
    url: jdbc:postgresql://imdb_database:5432/imdb
    username: ioasys
    password: ioasys
  flyway:
    enabled: on
    table: flyway_history
  jpa:
    hibernate:
      ddlAuto: validate
    openInView: true
    properties:
      hibernate:
        formatSql: true
        jdbc:
          lob:
            nonContextualCreation: true
      showSql: true
  main:
    bannerMode: off
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: always