spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imdb
    username: root
    password: ioasys
  flyway:
    enabled: on
    table: flyway_history
  jpa:
    hibernate:
      ddlAuto: validate
    openInView: false
    properties:
      hibernate:
        jdbc:
          lob:
            nonContextualCreation: true
        showSql: true
  main:
    bannerMode: off
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: always



